### ISSUE TITLE
nosuchmethod Exception in Android studio 2.2

### ISSUE THREAD

**Issue by wingsum93** [avast/android-butterknife-zelezny#115]
the plugin work as normal but it prompt message that it have NoSuchMethodException.
but in my observation it work properly.

org.jetbrains.android.resourceManagers.LocalResourceManager.findResourceFiles(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/util/List;

`org.jetbrains.android.resourceManagers.LocalResourceManager.findResourceFiles(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/util/List;
java.lang.NoSuchMethodError: org.jetbrains.android.resourceManagers.LocalResourceManager.findResourceFiles(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/util/List;
    at dk.erikzielke.android.butterknife.inspections.ButterKnifeNoViewWithIdInspection$MyJavaElementVisitor.checkIncludes(ButterKnifeNoViewWithIdInspection.java:187)
    at dk.erikzielke.android.butterknife.inspections.ButterKnifeNoViewWithIdInspection$MyJavaElementVisitor.handleValue(ButterKnifeNoViewWithIdInspection.java:132)
    at dk.erikzielke.android.butterknife.inspections.ButterKnifeNoViewWithIdInspection$MyJavaElementVisitor.visitAnnotation(ButterKnifeNoViewWithIdInspection.java:106)
    at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.accept(PsiAnnotationImpl.java:102)
    at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:64)
    at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:26)
    at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
    at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
    at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:73)
    at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
    at dk.erikzielke.android.butterknife.inspections.ButterKnifeNoViewWithIdInspection$MyJavaElementVisitor.visitElement(ButterKnifeNoViewWithIdInspection.java:80)
    at com.intellij.psi.JavaElementVisitor.visitClass(JavaElementVisitor.java:55)
    at dk.erikzielke.android.butterknife.inspections.ButterKnifeNoViewWithIdInspection$MyJavaElementVisitor.visitClass(ButterKnifeNoViewWithIdInspection.java:74)
    at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:473)
    at dk.erikzielke.android.butterknife.inspections.ButterKnifeNoViewWithIdInspection$RelatedLayoutFilesVisitor.findInFiles(ButterKnifeNoViewWithIdInspection.java:293)
    at dk.erikzielke.android.butterknife.inspections.ButterKnifeNoViewWithIdInspection$RelatedLayoutFilesVisitor.visitReferenceExpression(ButterKnifeNoViewWithIdInspection.java:257)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:715)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:128)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1181)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:112)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
`

**Comment by moheny** [comment]
This plugin does not work with android 2.2 (at least on my mac), correct me if i'm wrong.

**Comment by TomasKypta** [comment]
The issue is caused by android-butterknife-zelezny. 
It's another AS plugin for Butter Knife https://github.com/erikzielke/butterknife_inspections.

**Comment by wingsum93** [comment]
Thank you guys. Confirmed is butter knife plugin issue
