### ISSUE TITLE
Android Studio 1.1rc1 : ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Christophe668** [avast/android-butterknife-zelezny#40]
Hi,

I'm getting an error on Android Studio 1.1RC1 **ArrayIndexOutOfBoundsException: 0: 0** with the version 1.1 and 1.2 of the plugin when I selected "Generate Butterknife Injections".
the crash occurs instantly and the dialog doesn't appear.
I did not test it on previous version of Android Studio.

Any idea why this might be happening? 

Thanks

**Comment by destil** [comment]
I just tried with AS 1.1RC1 and it doesn't crash on my project. You need to give us more information about your class, layout, etc.

**Comment by Christophe668** [comment]
The crash occurs from a fragment.
You will find my code from a sample class that doesn't work.

Here's my xml :
```
<?xml version="1.0" encoding="utf-8"?>
<ScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="center">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:orientation="vertical"
        android:padding="@dimen/prf__padding_m">

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_action_report"/>

        <com.rengwuxian.materialedittext.MaterialEditText
            android:layout_marginTop="@dimen/prf__margin_m"
            android:id="@+id/prf__fragment_login_password_edit_text"
            style="@style/prf__SignInEditText"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:inputType="textEmailAddress"
            android:hint="@string/prf__to_be_translated"/>

        <com.rengwuxian.materialedittext.MaterialEditText
            android:id="@+id/prf__fragment_login_user_name_edit_view"
            style="@style/prf__SignInEditText"
            android:layout_width="wrap_content"
            android:hint="@string/prf__to_be_translated"
            android:imeOptions="actionGo"
            android:imeActionLabel="@string/prf__to_be_translated"
            android:inputType="textPassword"/>

        <com.devspark.robototextview.widget.RobotoButton
            android:id="@+id/prf__fragment_login_login_button"
            android:layout_marginTop="@dimen/prf__margin_m"
            style="@style/prf__SignInButton"
            android:layout_width="wrap_content"
            android:text="@string/prf__to_be_translated"
            android:layout_height="wrap_content"/>

    </LinearLayout>
</ScrollView>
```

And here is my Fragment : 

```
package be.alphanetworks.alpha.gui.fragments;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import be.alphanetworks.alpha.R;

public class LoginFragment extends BaseFragment {


	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
	}

	@Override
	public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
		return inflater.inflate(R.layout.anw__fragment_login, container, false);
	}

	@Override
	public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
		super.onViewCreated(view, savedInstanceState);

	}

}
```

And here's the crash log :

```
0: 0
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.avast.android.butterknifezelezny.model.Element.getFieldName(Element.java:79)
	at com.avast.android.butterknifezelezny.model.Element.<init>(Element.java:41)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:179)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1027)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:78)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:36)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:142)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1027)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:78)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:36)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:142)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1027)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:78)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:36)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:142)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlDocument(XmlElementVisitor.java:42)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.accept(XmlDocumentImpl.java:87)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:798)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:36)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:142)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:32)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitFile(XmlRecursiveElementVisitor.java:54)
	at com.intellij.psi.XmlElementVisitor.visitXmlFile(XmlElementVisitor.java:26)
	at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:71)
	at com.avast.android.butterknifezelezny.common.Utils.getIDsFromLayout(Utils.java:138)
	at com.avast.android.butterknifezelezny.common.Utils.getIDsFromLayout(Utils.java:128)
	at com.avast.android.butterknifezelezny.InjectAction.actionPerformedImpl(InjectAction.java:68)
	at com.avast.android.butterknifezelezny.InjectAction.actionPerformed(InjectAction.java:55)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:733)
	at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1248)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:651)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:632)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:602)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:108)
	at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by destil** [comment]
I debugged it and it's caused by your id names:

`@+id/prf__fragment_login_login_button`

Specifically the double underscore. If you replace it with single underscore, it works.

**Comment by Christophe668** [comment]
Great, good to know.

Thank you for your prompt answer

**Comment by cl2hz** [comment]
I'have the similar problem when I try to use AS with a new project  I cant use autocompletion dont show anything here is the output in my console:
-1: -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.intellij.util.indexing.ValueContainerImpl$IdBitSet.get(ValueContainerImpl.java:655)
	at com.intellij.util.indexing.ValueContainerImpl$IdBitSet.set(ValueContainerImpl.java:618)
	at com.intellij.util.indexing.ValueContainerImpl.addValue(ValueContainerImpl.java:65)
	at com.intellij.util.indexing.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:130)
	at com.intellij.util.indexing.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:80)
	at com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:427)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:398)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:121)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:109)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.getMergedData(ChangeTrackingValueContainer.java:121)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:78)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:73)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:259)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:232)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:75)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:94)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:221)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:142)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:132)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerBase.findClassInIndex(JavaFileManagerBase.java:154)
	at com.intellij.psi.impl.file.impl.JavaFileManagerBase.findClass(JavaFileManagerBase.java:147)
	at com.intellij.psi.impl.JavaPsiFacadeImpl$PsiElementFinderImpl.findClass(JavaPsiFacadeImpl.java:287)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:107)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:404)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$000(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:330)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:385)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:327)
	at com.intellij.psi.impl.source.PsiImportStatementBaseImpl.resolve(PsiImportStatementBaseImpl.java:64)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarationsNoGuess(PsiJavaFileBaseImpl.java:316)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:290)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:457)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$000(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:330)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:106)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:385)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:141)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:89)
	at com.intellij.psi.util.TypeConversionUtil$5.visitClassType(TypeConversionUtil.java:1303)
	at com.intellij.psi.util.TypeConversionUtil$5.visitClassType(TypeConversionUtil.java:1300)
	at com.intellij.psi.PsiClassType.accept(PsiClassType.java:223)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1300)
	at com.intellij.psi.util.MethodSignatureUtil.calcErasedParameterTypes(MethodSignatureUtil.java:77)
	at com.intellij.psi.util.MethodSignatureBase.getErasedParameterTypes(MethodSignatureBase.java:81)
	at com.intellij.psi.util.MethodSignatureBase.hashCode(MethodSignatureBase.java:96)
	at com.intellij.psi.util.MethodSignatureUtil$2.computeHashCode(MethodSignatureUtil.java:52)
	at com.intellij.psi.util.MethodSignatureUtil$2.computeHashCode(MethodSignatureUtil.java:49)
	at com.intellij.codeInsight.completion.scope.JavaCompletionProcessor$1.computeHashCode(JavaCompletionProcessor.java:56)
	at gnu.trove.TObjectHash.insertionIndex(TObjectHash.java:221)
	at gnu.trove.THashSet.add(THashSet.java:139)
	at com.intellij.codeInsight.completion.scope.JavaCompletionProcessor.execute(JavaCompletionProcessor.java:224)
	at com.intellij.psi.scope.processor.FilterScopeProcessor.execute(FilterScopeProcessor.java:73)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$2.execute(PsiReferenceExpressionImpl.java:505)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClassNotCached(PsiClassImplUtil.java:649)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:453)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:519)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.processVariants(PsiReferenceExpressionImpl.java:509)
	at com.intellij.codeInsight.completion.JavaCompletionUtil.processJavaReference(JavaCompletionUtil.java:364)
	at com.intellij.codeInsight.completion.JavaCompletionContributor$5.consume(JavaCompletionContributor.java:312)
	at com.intellij.codeInsight.completion.JavaCompletionContributor$5.consume(JavaCompletionContributor.java:300)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:123)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:106)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.addReferenceVariants(JavaCompletionContributor.java:300)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.fillCompletionVariants(JavaCompletionContributor.java:239)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:112)
	at com.intellij.codeInsight.completion.JavaNoVariantsDelegator.fillCompletionVariants(JavaNoVariantsDelegator.java:46)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:75)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:115)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:769)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$900(CompletionProgressIndicator.java:84)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:751)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:911)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)

**Comment by NermineMunla** [comment]
http://envyandroid.com/arrayindexoutofboundsexception-listadapter/
