### ISSUE TITLE
IDE Fatal Errors

### ISSUE THREAD

**Issue by johnwatsondev** [avast/android-butterknife-zelezny#57]
Mac OS X 10.10.4
Android Studio 1.2.2 
android-butterknife-zelezny 1.3 just updated

```java
Argument for @NotNull parameter 'butterKnife' of com/avast/android/butterknifezelezny/navigation/NavigationMarkerProvider$ButterKnifeLink.getButterKnifeLink must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'butterKnife' of com/avast/android/butterknifezelezny/navigation/NavigationMarkerProvider$ButterKnifeLink.getButterKnifeLink must not be null
	at com.avast.android.butterknifezelezny.navigation.NavigationMarkerProvider$ButterKnifeLink.getButterKnifeLink(NavigationMarkerProvider.java)
	at com.avast.android.butterknifezelezny.navigation.NavigationMarkerProvider.getLineMarkerInfo(NavigationMarkerProvider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.addLineMarkers(LineMarkersPass.java:166)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:105)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

Here is some SNAPSHOT:

<img width="480" alt="qq20150716-2" src="https://cloud.githubusercontent.com/assets/12760754/8717110/8441ae86-2bca-11e5-8aac-61a7bc3566ec.png">

<img width="708" alt="qq20150716-3" src="https://cloud.githubusercontent.com/assets/12760754/8717113/8b8cde22-2bca-11e5-8ca0-3f835d5288b6.png">

Have any suggestion ？

**Comment by mtrakal** [comment]
Same issue on Windows with latest Android Studio canary build.1.3.

**Comment by destil** [comment]
Hi, thanks for the report. What did you do before it happened?

**Comment by mtrakal** [comment]
Just open Studio with project which used older (6.x) ButterKnife and gradle sync/build started. It made three times maybe. After I change one project to ButterKnife 7 it stops crashing. I can't reproduce it now... :(

**Comment by johnwatsondev** [comment]
It happened automatically after I updated plugin. I just opened my project as before and AS reported this issue repeatedly. I closed the plugin two hours ago finally.

It no more happened strangely when I enabled plugin again this moment !!!

I will be attention this issue. :joy_cat:

**Comment by tomik-dev** [comment]
Hi, yes, it's bug in our plugin caused when no ButterKnife version is found on the module classpath.
I'm working on a fix.
