### ISSUE TITLE
IDE Fatal Errors AGAIN...

### ISSUE THREAD

**Issue by johnwatsondev** [avast/android-butterknife-zelezny#60]
I'm sorry saw that after I updated to Version 1.3.1 yesterday.

It report another NullPointerException.

```java
java.lang.NullPointerException
	at com.avast.android.butterknifezelezny.common.Utils.isClassAvailableForPsiFile(Utils.java:314)
	at com.avast.android.butterknifezelezny.butterknife.ButterKnifeFactory.findButterKnifeForPsiElement(ButterKnifeFactory.java:45)
	at com.avast.android.butterknifezelezny.navigation.NavigationMarkerProvider.getLineMarkerInfo(NavigationMarkerProvider.java:90)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.addLineMarkers(LineMarkersPass.java:166)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:105)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

Thanks for fix this bug in advance~

**Comment by tomik-dev** [comment]
Ok, a different problem. I'm working on it. It seems that that the file cannot be located in any module.

**Comment by tomik-dev** [comment]
Hi, could you test this build https://www.dropbox.com/s/6ance9z7roaut9b/android-butterknife-zelezny-1.3.2.jar?dl=0 that everything is working for you. You seem to have some juicy projects ;)

**Comment by johnwatsondev** [comment]
@tomik-dev I have downloaded. I'm testing now. Plz waiting my response~

**Comment by johnwatsondev** [comment]
@tomik-dev Congratulation! It's worked. Ready to release!

**Comment by tomik-dev** [comment]
OK, good to hear it. It's out.
